{{ if eq .Values.chartMode "authoritative" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-named-conf
stringData:
  named.conf: |
    options {
      directory "/var/cache/bind";

      {{ if .Values.authoritative.dnssec_validation -}}
      dnssec-validation yes;
      {{- else -}}
      dnssec-validation no;
      {{- end }}
      listen-on port 5053 { any; };
      {{ if .Values.authoritative.ipv6_enabled -}}
      listen-on-v6 5053 { any; };
      {{- else -}}
      listen-on-v6 { none; };
      {{- end }}
      recursion no;
      allow-query { any; };

      {{ if .Values.authoritative.querylog -}}
      querylog yes;
      {{- else -}}
      querylog no;
      {{- end }}

    };
    {{ if .Values.mount_configuration_from_secret.enabled -}}
    include "/named_config/named.conf.local";
    {{- end }}

    // use the default zones
    include "/etc/bind/named.conf.default-zones";
{{- end }}
