apiVersion: v1
kind: Service
metadata:
  name: {{ include "bind9.fullname" . }}-dns-udp
  labels:
    {{- include "bind9.labels" . | nindent 4 }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "bind9.selectorLabels" . | nindent 4 }}
